<template>
  <div>

    <!-- Header -->
    <div class="flex items-center justify-between mb-8">
      <div>
        <h2 class="text-xl font-bold text-gray-900 tracking-tight">AI Insights</h2>
        <p class="text-sm text-gray-400 mt-0.5">Analyses generated by Claude</p>
      </div>
      <div class="flex items-center gap-2 bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-100 rounded-xl px-3 py-2">
        <div class="w-2 h-2 rounded-full bg-blue-500 animate-pulse"/>
        <span class="text-xs font-semibold text-blue-700">Claude AI</span>
      </div>
    </div>

    <!-- Generator card -->
    <div class="bg-gradient-to-br from-blue-600 to-indigo-700 rounded-2xl p-6 mb-6 shadow-xl shadow-blue-200/50">
      <div class="flex items-start gap-4">
        <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center flex-shrink-0">
          <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/>
          </svg>
        </div>
        <div class="flex-1 min-w-0">
          <h3 class="text-white font-bold text-base mb-1">Generate an analysis</h3>
          <p class="text-blue-200 text-sm mb-4">Claude analyzes your metrics and delivers an actionable business report.</p>

          <div class="flex flex-wrap gap-3">
            <select v-model="selectedCategory" :disabled="store.isStreaming"
              class="bg-white/20 border border-white/30 text-white rounded-xl px-3 py-2 text-sm font-medium focus:outline-none focus:bg-white/30 transition-all backdrop-blur-sm">
              <option value="Sales"     class="text-gray-900 bg-white">Sales</option>
              <option value="Marketing" class="text-gray-900 bg-white">Marketing</option>
              <option value="Support"   class="text-gray-900 bg-white">Support</option>
            </select>

            <button @click="generate" :disabled="store.isStreaming"
              class="flex items-center gap-2 px-5 py-2 bg-white text-blue-700 text-sm font-bold rounded-xl hover:bg-blue-50 transition-all disabled:opacity-60 shadow-lg">
              <div v-if="store.isStreaming" class="w-4 h-4 border-2 border-blue-700 border-t-transparent rounded-full animate-spin"/>
              <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
              </svg>
              {{ store.isStreaming ? 'Analyzing...' : 'Analyze with Claude' }}
            </button>
          </div>
        </div>
      </div>

      <!-- Streaming output -->
      <div v-if="store.isStreaming || streamDone" class="mt-5 bg-white/10 backdrop-blur-sm border border-white/20 rounded-xl p-4">
        <div class="flex items-center gap-2 mb-3">
          <div class="w-2 h-2 rounded-full bg-green-400 animate-pulse"/>
          <span class="text-xs font-semibold text-white/80 uppercase tracking-wide">
            {{ store.isStreaming ? 'Generating...' : 'Complete' }}
          </span>
        </div>
        <div class="text-white/90 text-sm leading-relaxed whitespace-pre-line font-mono">
          {{ store.streamContent }}
          <span v-if="store.isStreaming" class="inline-block w-1.5 h-4 bg-white animate-pulse ml-0.5 align-middle rounded-sm"/>
        </div>
      </div>

      <!-- Messages -->
      <div v-if="successMsg" class="mt-4 bg-green-500/20 border border-green-400/30 text-green-100 rounded-xl p-3 text-sm flex items-center gap-2">
        <svg class="w-4 h-4 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
        </svg>
        {{ successMsg }}
      </div>
      <div v-if="store.error" class="mt-4 bg-red-500/20 border border-red-400/30 text-red-100 rounded-xl p-3 text-sm">
        {{ store.error }}
      </div>
    </div>

    <!-- History header -->
    <div class="flex items-center justify-between mb-4">
      <h3 class="text-sm font-bold text-gray-900">Analysis history</h3>
      <div class="flex gap-1.5">
        <button
          v-for="cat in ['All', 'Sales', 'Marketing', 'Support']" :key="cat"
          @click="filterCategory = cat"
          class="px-3 py-1.5 rounded-xl text-xs font-semibold transition-all"
          :class="filterCategory === cat
            ? 'bg-blue-600 text-white shadow-md shadow-blue-200'
            : 'bg-white border border-gray-100 text-gray-500 hover:bg-gray-50 shadow-sm'"
        >
          {{ cat }}
        </button>
      </div>
    </div>

    <!-- Loading history -->
    <div v-if="loadingHistory" class="flex justify-center h-32 items-center">
      <div class="w-8 h-8 border-3 border-blue-500 border-t-transparent rounded-full animate-spin"/>
    </div>

    <!-- Empty -->
    <div v-else-if="filteredInsights.length === 0"
      class="bg-white border border-gray-100 rounded-2xl p-12 text-center shadow-sm">
      <div class="w-12 h-12 bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl flex items-center justify-center mx-auto mb-4">
        <svg class="w-6 h-6 text-blue-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/>
        </svg>
      </div>
      <p class="text-sm font-semibold text-gray-400">No analyses yet</p>
      <p class="text-xs text-gray-300 mt-1">Start your first analysis above</p>
    </div>

    <!-- Insights list -->
    <div v-else class="space-y-4">
      <InsightCard v-for="insight in filteredInsights" :key="insight.id" :insight="insight"/>
    </div>

  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useInsightsStore } from '../stores/insightsStore'
import InsightCard from '../components/InsightCard.vue'

const store            = useInsightsStore()
const selectedCategory = ref('Sales')
const filterCategory   = ref('All')
const successMsg       = ref('')
const loadingHistory   = ref(false)
const streamDone       = ref(false)

onMounted(async () => {
  loadingHistory.value = true
  await store.fetchInsights()
  loadingHistory.value = false
})

const filteredInsights = computed(() =>
  filterCategory.value === 'All'
    ? store.insights
    : store.insights.filter(i => i.category === filterCategory.value)
)

async function generate() {
  streamDone.value = false
  try {
    await store.streamInsight(selectedCategory.value)
    streamDone.value = true
    successMsg.value = 'Analysis saved successfully.'
    setTimeout(() => { successMsg.value = ''; streamDone.value = false }, 5000)
  } catch { /* error handled in store */ }
}
</script>